name: openai_core
description: openai support for dart
version: 0.0.1
homepage: https://github.com
documentation: https://github.com

environment:
  sdk: '^3.2.0'
  
dependencies:
  http: ^1.4.0
  test: ^1.26.2
