name: openai_core
description: openai support for dart including the responses api, the realtime api, and more.
version: 0.6.0
homepage: https://github.com/meshagent/openai_core
documentation: https://github.com/meshagent/openai_core

environment:
  sdk: '^3.2.0'
  
dependencies:
  http_parser: ^4.1.2
  http: ^1.4.0
  mime: ^2.0.0
  test: ^1.26.2
  web_socket_channel: ^3.0.3

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
