name: Publish to pub.dev

on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  publish:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        run: dart pub get
      - name: Publish
        run: dart pub publish --force
